import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Section from 'components/Section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>kStore | Kate Gonzalez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Section/>
      </main>
    </div>
  )
}
